# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua Gonzales
description: "I'm a first-year law student at UC Davis School of Law. With my background in engineering and network computing, I aim to specialize in digital privacy and help companies fulfill their legal and technical obligations toward protecting user data."
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://joshua.bio' # the base hostname & protocol for your site
facebook_image: ''
type: 'article'
twitter: '@joshuadotbio'
facebook: 'jfmgonzales'
snapchat: 'jjfmg'

categories:

# Build settings
markdown: kramdown
timezone: 'America/Los_Angeles'

# Options
permalink: /:title
exclude:
  - 'node_modules'
  - 'bower_components'
  - 'bower.json'
  - 'package.json'
  - 'gulpfile.js'
  - 'Gemfile'
  - 'Gemfile.lock'
keep_files:
  - '.htaccess'
sass:
  style: compressed
  sass_dir: _sass
